# Generated by Django 6.0.5 on 2026-05-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='titulo')),
                ('file', models.FileField(upload_to='documents/originals/', verbose_name='arquivo PDF')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='documents/processed/', verbose_name='arquivo processado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-updated_at'],
            },
        ),
    ]
