# Generated by Django 6.0.5 on 2026-05-28 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0002_document_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('pdf_to_jpg', 'PDF para JPG'), ('office_to_pdf', 'Documento para PDF'), ('images_to_pdf', 'Imagem para PDF'), ('merge', 'Juntar PDFs'), ('edit', 'Edicao de PDF')], max_length=40, verbose_name='operacao')),
                ('source_name', models.CharField(blank=True, max_length=255, verbose_name='arquivo de origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'processamento',
                'verbose_name_plural': 'processamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
