# Generated by Django 6.0.5 on 2026-05-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0003_processinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinglog',
            name='operation',
            field=models.CharField(choices=[('pdf_to_jpg', 'PDF para JPG'), ('office_to_pdf', 'Documento para PDF'), ('images_to_pdf', 'Imagem para PDF'), ('merge', 'Juntar PDFs'), ('upload', 'Upload de PDF'), ('rotate', 'Girar paginas'), ('extract', 'Extrair paginas'), ('delete_pages', 'Excluir paginas'), ('reorder', 'Reordenar paginas'), ('protect', 'Proteger arquivo'), ('text', 'Inserir texto'), ('replace_text', 'Substituir texto'), ('image', 'Inserir imagem'), ('signature', 'Assinatura visual'), ('watermark', 'Marca dagua'), ('shape', 'Forma grafica'), ('qr_code', 'QR Code')], max_length=40, verbose_name='operacao'),
        ),
    ]
